/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_thread_MyThread */

#ifndef _Included_com_example_test_thread_MyThread
#define _Included_com_example_test_thread_MyThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_thread_MyThread
 * Method:    mainThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_test_thread_MyThread_mainThread
  (JNIEnv *, jobject);

/*
 * Class:     com_example_test_thread_MyThread
 * Method:    setJNIEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_test_thread_MyThread_setJNIEnv
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
